import { BusinessRule, ClientScript, StringColumn, Table } from '@servicenow/sdk/core'
import '@servicenow/sdk/global'
import { showStateUpdate } from '../server/script.js'

//creates a client script that pops up 'Table loaded successfully!!' message every time todo record is loaded
ClientScript({
    $id: Now.ID['cs0'],
    name: 'my_client_script',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!!")
    }`,
})

//creates a business rule that pops up state change message whenever a todo record is updated
BusinessRule({
    $id: Now.ID['br0'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange',
    order: 100,
    when: 'after',
    active: true,
})

export const x_snc_sso_lrm_test_legal_request = Table({
    name: 'x_snc_sso_lrm_test_legal_request',
    label: 'Legal Request',
    scriptable_table: false,
    allow_web_service_access: true,
    allow_new_fields: false,
    allow_client_scripts: false,
    allow_ui_actions: false,
    extensible: false,
    accessible_from: 'public',
    actions: ['read'],
    schema: {
        number: StringColumn({
            label: 'Number',
            attributes: {
                ignore_filter_on_new: true,
            },
            maxLength: 40,
            default: 'javascript:global.getNextObjNumberPadded();',
        }),
        request_reason: StringColumn({
            label: 'Request Reason',
            maxLength: 40,
        }),
        request_type: StringColumn({
            label: 'Request Type',
            maxLength: 40,
        })
    },
})

export const x_snc_sso_lrm_test_legal_request_1 = Table({
    name: 'x_snc_sso_lrm_test_legal_request_1',
    label: 'Legal Request 1',
    scriptable_table: false,
    allow_web_service_access: true,
    allow_new_fields: false,
    allow_client_scripts: false,
    allow_ui_actions: false,
    extensible: false,
    accessible_from: 'public',
    actions: ['read'],
    schema: {
        number: StringColumn({
            label: 'Number',
            attributes: {
                ignore_filter_on_new: true,
            },
            maxLength: 40,
            default: 'javascript:global.getNextObjNumberPadded();',
        }),
        request_reason: StringColumn({
            label: 'Request Reason',
            maxLength: 40,
        }),
        request_type: StringColumn({
            label: 'Request Type',
            maxLength: 40,
        })
    },
})
